apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: cleanup-agent-manager
  name: test-infra-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanup-agent-manager
  namespace: test-infra-system
  labels:
    control-plane: cleanup-agent-manager
spec:
  selector:
    matchLabels:
      control-plane: cleanup-agent-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: cleanup-agent-manager
    spec:
      nodeSelector:
        default-system-pool: "true"
      containers:
      - command:
        image: cleanup_agent:latest
        name: manager
      terminationGracePeriodSeconds: 10
