# See ../pkg/defaults/defaults.go for documentation on each field.

driverPool: drivers

workerPool: workers-16core

driverPort: 10000

serverPort: 10010

cloneImage: docker.pkg.github.com/grpc/test-infra/clone

driverImage: docker.pkg.github.com/grpc/test-infra/driver

languages:
  - name: cxx
    buildImage: l.gcr.io/google/bazel:latest
    runImage: docker.pkg.github.com/grpc/test-infra/cxx

  - name: java
    buildImage: gradle:jdk8
    runImage: docker.pkg.github.com/grpc/test-infra/java

  - name: go
    buildImage: golang:1.14
    runImage: docker.pkg.github.com/grpc/test-infra/go
